In [1]:
import pandas as pd

In [2]:
data_set_2008 = pd.read_csv(r"C:\Users\manas\Downloads\ipl\IPL - Player Performance Dataset\Most Runs Over\Most Runs Over - 2008.csv")

In [3]:
data_set_2008.head()

,POS,Player,Runs,BF,SR,4s,6s,Against,Venue,Match Date
0,1,Virender Sehwag,30,6,500.00,3,3,DEC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008
1,2,Sanath Jayasuriya,26,5,520.00,2,3,CSK,Wankhede Stadium,14 May 2008
2,3,MF Maharoof,26,5,520.00,0,4,RR,Sawai Mansingh Stadium,11 May 2008
3,4,Rohit Sharma,26,6,433.33,3,2,DC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008
4,5,Shane Watson,26,6,433.33,5,1,RCB,M. Chinnaswamy Stadium,26 April 2008

In [5]:
IPL_Data = {}

for year in range(2008,2022):
    IPL_Data[year] = pd.read_csv(rf"C:\Users\manas\Downloads\ipl\IPL - Player Performance Dataset\Most Runs Over\Most Runs Over - {year}.csv")
for i,j in IPL_Data.items():
    print(i,"-->",j)

2008 -->      POS                 Player  Runs  BF      SR  4s  6s Against  \
0      1        Virender Sehwag    30   6  500.00   3   3     DEC
1      2      Sanath Jayasuriya    26   5  520.00   2   3     CSK
2      3            MF Maharoof    26   5  520.00   0   4      RR
3      4           Rohit Sharma    26   6  433.33   3   2      DC
4      5           Shane Watson    26   6  433.33   5   1     RCB
..   ...                    ...   ...  ..     ...  ..  ..     ...
145  146         Gautam Gambhir    13   5  260.00   3   0     RCB
146  147  Subramaniam Badrinath    13   5  260.00   0   2    PBKS
147  148         Michael Hussey    13   4  325.00   1   1    PBKS
148  149           Yusuf Pathan    13   4  325.00   3   0    PBKS
149  150        Stephen Fleming    13   5  260.00   1   1     RCB

                                  Venue     Match Date
0    Rajiv Gandhi Intl. Cricket Stadium  22 April 2008
1                      Wankhede Stadium    14 May 2008
2                Sawai Mansingh Stadium    11 May 2008
3    Rajiv Gandhi Intl. Cricket Stadium  22 April 2008
4                M. Chinnaswamy Stadium  26 April 2008
..                                  ...            ...
145                Arun Jaitley Stadium  30 April 2008
146                         Chidambaram    10 May 2008
147                   IS Bindra Stadium  19 April 2008
148                   IS Bindra Stadium    28 May 2008
149                         Chidambaram    21 May 2008

[150 rows x 10 columns]
2009 -->      POS             Player  Runs  BF      SR  4s  6s Against  \
0      1       David Hussey    25   7  357.14   2   2     DEC
1      2           MS Dhoni    24   6  400.00   2   2    PBKS
2      3     Adam Gilchrist    23   6  383.33   1   3      DC
3      4       Rohit Sharma    22   6  366.66   2   2     KKR
4      5   Brendon McCullum    22   6  366.66   4   1     CSK
..   ...                ...   ...  ..     ...  ..  ..     ...
145  146       Dwayne Bravo    11   5  220.00   0   1    PBKS
146  147    Ravindra Jadeja    11   4  275.00   1   1     CSK
147  148           MS Dhoni    11   4  275.00   2   0    PBKS
148  149  Dwaraka Ravi Teja    11   6  183.33   2   0      DC
149  150    Ravindra Jadeja    11   6  183.33   2   0      MI

                     Venue   Match Date
0    New Wanderers Stadium  16 May 2009
1          Supersport Park  07 May 2009
2          Supersport Park  22 May 2009
3    New Wanderers Stadium  16 May 2009
4          Supersport Park  18 May 2009
..                     ...          ...
145        Supersport Park  12 May 2009
146  De Beers Diamond Oval  09 May 2009
147        Supersport Park  07 May 2009
148              Kingsmead  13 May 2009
149              Kingsmead  14 May 2009

[150 rows x 10 columns]
2010 -->      POS             Player  Runs  BF      SR  4s  6s Against  \
0      1      Robin Uthappa    25   6  416.66   1   3    PBKS
1      2       Murali Vijay    24   6  400.00   3   2      RR
2      3       Yusuf Pathan    24   5  480.00   3   2      MI
3      4     Kieron Pollard    24   5  480.00   1   3      DC
4      5        Chris Gayle    24   4  600.00   0   4    PBKS
..   ...                ...   ...  ..     ...  ..  ..     ...
145  146     Andrew Symonds    13   5  260.00   0   2      DC
146  147          JP Duminy    13   4  325.00   3   0      DC
147  148     Saurabh Tiwary    13   5  260.00   3   0     KKR
148  149        Ryan Harris    13   4  325.00   1   1     CSK
149  150  Sanath Jayasuriya    13   6  216.66   3   0      RR

                      Venue     Match Date
0    M. Chinnaswamy Stadium  16 March 2010
1     Narendra Modi Stadium  28 March 2010
2         Brabourne Stadium  13 March 2010
3         Brabourne Stadium  13 April 2010
4              Eden Gardens  04 April 2010
..                      ...            ...
145    Arun Jaitley Stadium  18 April 2010
146       Brabourne Stadium  13 April 2010
147       Brabourne Stadium  22 March 2010
148        DY Patil Stadium  22 April 2010
149       Brabourne Stadium  13 March 2010

[150 rows x 10 columns]
2011 -->      POS                 Player  Runs  BF      SR  4s  6s Against  \
0      1            Chris Gayle    36   7  514.28   3   4     KTK
1      2            Shaun Marsh    30   6  500.00   3   3     RCB
2      3           Yuvraj Singh    24   5  480.00   1   3      DC
3      4            Shaun Marsh    24   5  480.00   1   3      DC
4      5          Paul Valthaty    24   7  342.85   3   2      RR
..   ...                    ...   ...  ..     ...  ..  ..     ...
145  146         Mayank Agarwal    13   5  260.00   1   1      MI
146  147     Srikkanth Anirudha    13   5  260.00   3   0     KKR
147  148  Subramaniam Badrinath    13   4  325.00   1   1      DC
148  149  Subramaniam Badrinath    13   5  260.00   2   0    PBKS
149  150            Chris Gayle    13   3  433.33   0   2    PBKS

                      Venue     Match Date
0    M. Chinnaswamy Stadium    08 May 2011
1              HPCA Stadium    17 May 2011
2          DY Patil Stadium  17 April 2011
3              HPCA Stadium    15 May 2011
4         IS Bindra Stadium  21 April 2011
..                      ...            ...
145             Chidambaram    27 May 2011
146             Chidambaram  08 April 2011
147             Chidambaram    12 May 2011
148       IS Bindra Stadium  13 April 2011
149  M. Chinnaswamy Stadium    06 May 2011

[150 rows x 10 columns]
2012 -->      POS                Player  Runs  BF      SR  4s  6s Against  \
0      1           Chris Gayle    30   5  600.00   0   5     PWI
1      2          Albie Morkel    28   6  466.66   2   3     RCB
2      3           Chris Gayle    24   5  480.00   0   4     PWI
3      4           Chris Gayle    24   6  400.00   3   2     DEC
4      5        Mayank Agarwal    24   6  400.00   2   2      MI
..   ...                   ...   ...  ..     ...  ..  ..     ...
145  146        Mayank Agarwal    13   5  260.00   0   2     CSK
146  147        Gautam Gambhir    13   5  260.00   1   1    PBKS
147  148           Chris Gayle    13   6  216.66   3   0     KKR
148  149  Tillakaratne Dilshan    13   4  325.00   3   0     PWI
149  150            Naman Ojha    13   3  433.33   0   2    PBKS

                                                 Venue     Match Date
0                               M. Chinnaswamy Stadium  17 April 2012
1                                          Chidambaram  12 April 2012
2    Maharashtra Cricket Association's Internationa...    11 May 2012
3                   Rajiv Gandhi Intl. Cricket Stadium    20 May 2012
4                               M. Chinnaswamy Stadium    14 May 2012
..                                                 ...            ...
145                                        Chidambaram  12 April 2012
146                                  IS Bindra Stadium  18 April 2012
147                                       Eden Gardens  28 April 2012
148  Maharashtra Cricket Association's Internationa...    11 May 2012
149                               Arun Jaitley Stadium    15 May 2012

[150 rows x 10 columns]
2013 -->      POS          Player  Runs  BF      SR  4s  6s Against  \
0      1     Chris Gayle    28   6  466.66   1   4     PWI
1      2     Chris Gayle    28   5  560.00   1   4     PWI
2      3     Chris Gayle    26   5  520.00   2   3     PWI
3      4  AB de Villiers    26   6  433.33   3   2     PWI
4      5    Rohit Sharma    26   6  433.33   2   3    PBKS
..   ...             ...   ...  ..     ...  ..  ..     ...
145  146    Dwayne Smith    13   4  325.00   1   1     KKR
146  147    Shane Watson    13   5  260.00   1   1     CSK
147  148    Shane Watson    13   3  433.33   0   2      MI
148  149    Stuart Binny    13   5  260.00   1   1     PWI
149  150  Adam Gilchrist    13   3  433.33   0   2     RCB

                                                 Venue     Match Date
0                               M. Chinnaswamy Stadium  23 April 2013
1                               M. Chinnaswamy Stadium  23 April 2013
2                               M. Chinnaswamy Stadium  23 April 2013
3    Maharashtra Cricket Association's Internationa...    02 May 2013
4                                     Wankhede Stadium  29 April 2013
..                                                 ...            ...
145                                       Eden Gardens  24 April 2013
146                                        Chidambaram  22 April 2013
147                                   Wankhede Stadium    15 May 2013
148                             Sawai Mansingh Stadium    05 May 2013
149                             M. Chinnaswamy Stadium    14 May 2013

[150 rows x 10 columns]
2014 -->      POS            Player  Runs  BF      SR  4s  6s Against  \
0      1      Suresh Raina    32   7  457.14   5   2    PBKS
1      2      Yusuf Pathan    26   6  433.33   3   2     SRH
2      3      David Miller    26   5  520.00   0   4      RR
3      4    Kieron Pollard    26   6  433.33   1   3     SRH
4      5          MS Dhoni    24   6  400.00   2   2     SRH
..   ...               ...   ...  ..     ...  ..  ..     ...
145  146  Brendon McCullum    13   6  216.66   2   0     KKR
146  147    Shikhar Dhawan    13   6  216.66   3   0     KKR
147  148      Dwayne Smith    13   6  216.66   0   2      MI
148  149      Dwayne Smith    13   5  260.00   3   0      MI
149  150       Shaun Marsh    13   4  325.00   1   1      MI

                           Venue     Match Date
0               Wankhede Stadium    30 May 2014
1                   Eden Gardens    24 May 2014
2        Sharjah Cricket Stadium  20 April 2014
3    Dubai International Stadium  30 April 2014
4                   JSCA Stadium    22 May 2014
..                           ...            ...
145                 JSCA Stadium    02 May 2014
146                 Eden Gardens    24 May 2014
147  Dubai International Stadium  25 April 2014
148            Brabourne Stadium    28 May 2014
149            IS Bindra Stadium    21 May 2014

[150 rows x 10 columns]
2015 -->      POS          Player  Runs  BF      SR  4s  6s Against  \
0      1     Chris Gayle    24   6  400.00   3   2     SRH
1      2    Rohit Sharma    23   5  460.00   1   3     RCB
2      3  Kieron Pollard    23   5  460.00   1   3     CSK
3      4  Kieron Pollard    22   5  440.00   1   3     CSK
4      5    David Miller    22   6  366.66   1   3     SRH
..   ...             ...   ...  ..     ...  ..  ..     ...
145  146    Suresh Raina    13   5  260.00   1   1     RCB
146  147  AB de Villiers    13   5  260.00   3   0      RR
147  148  AB de Villiers    13   4  325.00   0   2      MI
148  149   Manish Pandey    13   5  260.00   3   0    PBKS
149  150  Kieron Pollard    13   4  325.00   1   1      RR

                                  Venue     Match Date
0    Rajiv Gandhi Intl. Cricket Stadium    15 May 2015
1                M. Chinnaswamy Stadium  19 April 2015
2                      Wankhede Stadium  17 April 2015
3                          Eden Gardens    24 May 2015
4    Rajiv Gandhi Intl. Cricket Stadium    11 May 2015
..                                  ...            ...
145              M. Chinnaswamy Stadium  22 April 2015
146              M. Chinnaswamy Stadium  29 April 2015
147                    Wankhede Stadium    10 May 2015
148                        Eden Gardens    09 May 2015
149                    Wankhede Stadium    01 May 2015

[150 rows x 10 columns]
2016 -->      POS            Player  Runs  BF      SR  4s  6s Against  \
0      1       Virat Kohli    30   6  500.00   1   4      GL
1      2      Yusuf Pathan    24   6  400.00   4   1     RCB
2      3       Ben Cutting    23   5  460.00   1   3     RCB
3      4    AB de Villiers    23   6  383.33   1   3      GL
4      5  Brendon McCullum    22   6  366.66   3   1     RPS
..   ...               ...   ...  ..     ...  ..  ..     ...
145  146   Shakib Al Hasan    13   4  325.00   0   2      GL
146  147        Karun Nair    13   6  216.66   3   0     KKR
147  148   Harbhajan Singh    13   5  260.00   3   0     RPS
148  149    Kieron Pollard    13   3  433.33   0   2    PBKS
149  150    AB de Villiers    13   4  325.00   0   2     SRH

                                                 Venue     Match Date
0                               M. Chinnaswamy Stadium    14 May 2016
1                               M. Chinnaswamy Stadium    02 May 2016
2                               M. Chinnaswamy Stadium    29 May 2016
3                               M. Chinnaswamy Stadium    14 May 2016
4    Maharashtra Cricket Association's Internationa...  29 April 2016
..                                                 ...            ...
145                                       Eden Gardens    08 May 2016
146                               Arun Jaitley Stadium  30 April 2016
147                                   Wankhede Stadium  09 April 2016
148                                   ACA-VDCA Stadium    13 May 2016
149                             M. Chinnaswamy Stadium  12 April 2016

[150 rows x 10 columns]
2017 -->      POS           Player  Runs  BF      SR  4s  6s Against  \
0      1    Hardik Pandya    28   6  466.66   1   4     RPS
1      2    Glenn Maxwell    27   6  450.00   2   3      MI
2      3     Rishabh Pant    26   6  433.33   2   3     KKR
3      4     Sunil Narine    25   6  416.66   1   3     RCB
4      5     Kedar Jadhav    24   6  400.00   2   2      DC
..   ...              ...   ...  ..     ...  ..  ..     ...
145  146    Lendl Simmons    13   5  260.00   0   2    PBKS
146  147  Wriddhiman Saha    13   4  325.00   0   2     KKR
147  148     Kedar Jadhav    13   4  325.00   1   1      DC
148  149     David Warner    13   4  325.00   1   1     KKR
149  150   Rahul Tripathi    13   4  325.00   3   0     KKR

                                                 Venue     Match Date
0    Maharashtra Cricket Association's Internationa...  06 April 2017
1                               Holkar Cricket Stadium  20 April 2017
2                                 Arun Jaitley Stadium  17 April 2017
3                               M. Chinnaswamy Stadium    07 May 2017
4                               M. Chinnaswamy Stadium  08 April 2017
..                                                 ...            ...
145                                   Wankhede Stadium    11 May 2017
146                                       Eden Gardens  13 April 2017
147                             M. Chinnaswamy Stadium  08 April 2017
148                 Rajiv Gandhi Intl. Cricket Stadium  30 April 2017
149  Maharashtra Cricket Association's Internationa...  26 April 2017

[150 rows x 10 columns]
2018 -->      POS         Player  Runs  BF      SR  4s  6s Against  \
0      1   Shreyas Iyer    28   6  466.66   1   4     KKR
1      2    Jos Buttler    28   6  466.66   4   2     KKR
2      3   Rishabh Pant    26   5  520.00   2   3     SRH
3      4    Chris Gayle    26   5  520.00   0   4     SRH
4      5   Shane Watson    26   6  433.33   2   3     SRH
..   ...            ...   ...  ..     ...  ..  ..     ...
145  146   Shane Watson    14   4  350.00   0   2      DC
146  147  Andre Russell    14   6  233.33   2   1     RCB
147  148   Rohit Sharma    14   5  280.00   2   1     RCB
148  149   Rishabh Pant    14   6  233.33   2   1     RCB
149  150     Evin Lewis    14   6  233.33   2   1     KKR

                                                 Venue     Match Date
0                                 Arun Jaitley Stadium  27 April 2018
1                                         Eden Gardens    15 May 2018
2                                 Arun Jaitley Stadium    10 May 2018
3                                    IS Bindra Stadium  19 April 2018
4                                     Wankhede Stadium    27 May 2018
..                                                 ...            ...
145  Maharashtra Cricket Association's Internationa...  30 April 2018
146                                       Eden Gardens  08 April 2018
147                                   Wankhede Stadium  17 April 2018
148                             M. Chinnaswamy Stadium  21 April 2018
149                                   Wankhede Stadium    06 May 2018

[150 rows x 10 columns]
2019 -->      POS          Player  Runs  BF      SR  4s  6s Against  \
0      1   Andre Russell    28   5  560.00   1   4     RCB
1      2     Jos Buttler    28   6  466.66   4   2      MI
2      3       Moeen Ali    26   6  433.33   2   3     KKR
3      4        KL Rahul    24   6  400.00   3   2     CSK
4      5     Chris Gayle    24   6  400.00   3   2     RCB
..   ...             ...   ...  ..     ...  ..  ..     ...
145  146   Parthiv Patel    13   5  260.00   3   0      RR
146  147  Jonny Bairstow    13   4  325.00   0   2     CSK
147  148      Sam Curran    13   4  325.00   1   1     KKR
148  149        KL Rahul    13   3  433.33   0   2     SRH
149  150    Sanju Samson    13   5  260.00   2   0     SRH

                                  Venue     Match Date
0                M. Chinnaswamy Stadium  05 April 2019
1                      Wankhede Stadium  13 April 2019
2                          Eden Gardens  19 April 2019
3                     IS Bindra Stadium    05 May 2019
4                     IS Bindra Stadium  13 April 2019
..                                  ...            ...
145              Sawai Mansingh Stadium  02 April 2019
146  Rajiv Gandhi Intl. Cricket Stadium  17 April 2019
147                   IS Bindra Stadium    03 May 2019
148  Rajiv Gandhi Intl. Cricket Stadium  29 April 2019
149              Sawai Mansingh Stadium  27 April 2019

[150 rows x 10 columns]
2020 -->      POS            Player  Runs  BF      SR  4s  6s Against  \
0      1     Rahul Tewatia    30   6  500.00   0   5    PBKS
1      2   Nicholas Pooran    28   6  466.66   1   4     SRH
2      3    Kieron Pollard    27   6  450.00   1   3     RCB
3      4     Hardik Pandya    26   5  520.00   2   3      RR
4      5      Jofra Archer    26   7  371.42   0   4     CSK
..   ...               ...   ...  ..     ...  ..  ..     ...
145  146      Jofra Archer    13   3  433.33   0   2    PBKS
146  147       Jos Buttler    13   6  216.66   1   1     CSK
147  148  Devdutt Padikkal    13   5  260.00   0   2      MI
148  149       Aaron Finch    13   5  260.00   3   0      MI
149  150    Marcus Stoinis    13   5  260.00   3   0    PBKS

                           Venue         Match Date
0        Sharjah Cricket Stadium  27 September 2020
1    Dubai International Stadium    08 October 2020
2    Dubai International Stadium  28 September 2020
3          Zayed Cricket Stadium    25 October 2020
4        Sharjah Cricket Stadium  22 September 2020
..                           ...                ...
145      Sharjah Cricket Stadium  27 September 2020
146        Zayed Cricket Stadium    19 October 2020
147  Dubai International Stadium  28 September 2020
148  Dubai International Stadium  28 September 2020
149  Dubai International Stadium  20 September 2020

[150 rows x 10 columns]
2021 -->      POS           Player  Runs  BF      SR  4s  6s Against  \
0      1  Ravindra Jadeja    36   7  514.28   1   5     RCB
1      2      Pat Cummins    30   6  500.00   1   4     CSK
2      3     Prithvi Shaw    24   6  400.00   6   0     KKR
3      4   Mahipal Lomror    24   6  400.00   2   2    PBKS
4      5    Glenn Maxwell    22   6  366.66   3   1      RR
..   ...              ...   ...  ..     ...  ..  ..     ...
145  146  Ruturaj Gaikwad    13   6  216.66   1   1     KKR
146  147     Ishan Kishan    13   4  325.00   1   1     RCB
147  148    Mohammad Nabi    13   3  433.33   0   2      RR
148  149   Venkatesh Iyer    13   5  260.00   0   2      RR
149  150    Ambati Rayudu    13   5  260.00   1   1      DC

                           Venue         Match Date
0               Wankhede Stadium      25 April 2021
1               Wankhede Stadium      21 April 2021
2          Narendra Modi Stadium      29 April 2021
3    Dubai International Stadium  21 September 2021

In [6]:
for year,df in IPL_Data.items():
    df["Season"] = year

In [7]:
data_set_2008.head()

,POS,Player,Runs,BF,SR,4s,6s,Against,Venue,Match Date
0,1,Virender Sehwag,30,6,500.00,3,3,DEC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008
1,2,Sanath Jayasuriya,26,5,520.00,2,3,CSK,Wankhede Stadium,14 May 2008
2,3,MF Maharoof,26,5,520.00,0,4,RR,Sawai Mansingh Stadium,11 May 2008
3,4,Rohit Sharma,26,6,433.33,3,2,DC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008
4,5,Shane Watson,26,6,433.33,5,1,RCB,M. Chinnaswamy Stadium,26 April 2008

In [11]:
IPL_2008_2022 = pd.concat(IPL_Data.values(), ignore_index = True)
IPL_2008_2022.sample(10)
IPL_2008_2022.head()

,POS,Player,Runs,BF,SR,4s,6s,Against,Venue,Match Date,Season
0,1,Virender Sehwag,30,6,500.00,3,3,DEC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008,2008
1,2,Sanath Jayasuriya,26,5,520.00,2,3,CSK,Wankhede Stadium,14 May 2008,2008
2,3,MF Maharoof,26,5,520.00,0,4,RR,Sawai Mansingh Stadium,11 May 2008,2008
3,4,Rohit Sharma,26,6,433.33,3,2,DC,Rajiv Gandhi Intl. Cricket Stadium,22 April 2008,2008
4,5,Shane Watson,26,6,433.33,5,1,RCB,M. Chinnaswamy Stadium,26 April 2008,2008

In [12]:
IPL_2008_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   POS         2100 non-null   int64
 1   Player      2100 non-null   object
 2   Runs        2100 non-null   int64
 3   BF          2100 non-null   int64
 4   SR          2100 non-null   float64
 5   4s          2100 non-null   int64
 6   6s          2100 non-null   int64
 7   Against     2100 non-null   object
 8   Venue       2100 non-null   object
 9   Match Date  2100 non-null   object
 10  Season      2100 non-null   int64
dtypes: float64(1), int64(6), object(4)
memory usage: 180.6+ KB

In [13]:
IPL_2008_2022.shape

(2100, 11)